### ISSUE TITLE
False pass from travis/.../pr

### ISSUE THREAD

**Issue by mattmathis** [m-lab/etl-schema#57]
Since 'deploy" actually builds the target views, and travis/.../pr, skips deploy, pull requests end with 
spurious successful Travis runs.

**Comment by stephen-soltesz** [comment]
The successful result of travis for PRs is to run unit tests. PR travis runs measure a subset of "push" travis runs. PR travis runs are still necessary because not everyone uses sandbox-* branches for changes.

We discussed this in person. So, I believe this is resolved as WAI. Please re-open if there is still concern.
